export type DbTable =
  | 'profiles'
  | 'allowed_users'
  | 'products'
  | 'duties'
  | 'duty_major_categories'
  | 'product_assignments'
  | 'duty_assignments'
  | 'review_requests'
  | 'review_feedback'
  | 'projects'
  | 'project_assignments'
  | 'profile_notes'
  | 'activity_logs'
